### PR TITLE
Enable `pre-commit.ci`

### PR DESCRIPTION
**Pull request by sobolevn**
Testing `pre-commit.ci`

### CODE REVIEW

**Comment by sobolevn** [comment]
This commit https://github.com/typeddjango/django-stubs/pull/1222/commits/f03bff8487905aa049ba4b024820b08def9ea6e6 contains `black` violation.

We should get a new commit with the fix.

**Comment by sobolevn** [comment]
And here we go: https://github.com/typeddjango/django-stubs/pull/1222/commits/2306d98611764a322da82bc1ec6930fc4649c61e 🎉

**Comment by adamchainz** [comment]
Sick!

**Comment by adamchainz** [comment]
Why skip flake8?

**Comment by sobolevn** [comment]
I think `flake8` has no autofixes. 
And since we check `flake8` in `lint` job, there's no need to duplicate it.

**Comment by adamchainz** [comment]
pre-commit.ci isn’t only for tools with autofixes. It presents the output of linters like flake8 in its UI. I think we don’t need to run pre-commit twice, we can just use pre-commit.ci for everything. That’s what I do on my projects. Opened #1250 to do so.

**Pull request merged**
