### PR TITLE
Improve precision of BaseManager.from_queryset type annotation

### PR DESCRIPTION
**Pull request by youssefm**
According to django docs, from_queryset returns a subclass of the manager class it is called on

> For advanced usage you might want both a custom Manager and a custom QuerySet. You can do that by calling Manager.from_queryset() which returns a subclass of your base Manager with a copy of the custom QuerySet method

### CODE REVIEW

**Comment by mkurnikov** [comment]
This one should be addressed by the plugin in the `get_dynamic_class_hook`. Till then, it's better to return `Any` in order to avoid false-positives.

**Comment by youssefm** [comment]
not sure I follow - what false positives are you referring to?

**Comment by youssefm** [comment]
Is the concern that this wouldn't handle the methods that were copied over from the queryset class?

**Comment by mkurnikov** [comment]
Yes. Return type should be an `Intersection[_M, queryset_class]`, https://github.com/python/typing/issues/213

**Comment by youssefm** [comment]
I see - thanks for explaining

**Pull request closed without merging**
