### PR TITLE
adjust bases in CreateModel to allow for mixins

### PR DESCRIPTION
**Pull request by asottile**
# I have made things!

we have a few migrations which create models that have additional base classes

### CODE REVIEW

**Comment by sobolevn** [comment]
Let me understand this a little bit better: so, you have, say, a model like `class MyModel(SomeMixin, models.Model): ...`

And this type does not allow to run a `CreateModel` opetation on it?
I suspect that this might be a mypy bug 🤔

**Comment by sobolevn** [comment]
`MyModel` still should be `type[Model]`

**Comment by asottile** [comment]
> Let me understand this a little bit better: so, you have, say, a model like `class MyModel(SomeMixin, models.Model): ...`
> 
> And this type does not allow to run a `CreateModel` opetation on it? I suspect that this might be a mypy bug 🤔

for example https://github.com/getsentry/sentry/pull/56087/files#diff-a3e504055395e3cb856d99f4bc647fd048e61a1d75fa75fcc601877f62b88903R2283

**Review by sobolevn — APPROVED** [review]
Oh, I see 👍

**Pull request merged**
