### PR TITLE
Version 1.16.0 release

### LINKED ISSUE #1372: Next release planning (1.16.0; django-stubs-ext 0.8.0)
Will be making a release soon-ish (TM). If someone is waiting to get their PR reviewed, or a merged PR released, please mention here.

### PR DESCRIPTION
**Pull request by intgr**
## Related issues

Closes #1372.

### CODE REVIEW

**Review by adamchainz — APPROVED** [review]
LGTM

You're lead maintainer now? I missed that discussion. But congrats!

**Comment by intgr** [comment]
> You're lead maintainer now? I missed that discussion. But congrats!

Wasn't a big ceremony :D but the discussion took place at https://github.com/typeddjango/djangorestframework-stubs/pull/359#discussion_r1114331337

**Comment by intgr** [comment]
~~FWIW I'm still waiting to be able to release django-stubs-ext (https://github.com/typeddjango/django-stubs/pull/1395#issuecomment-1470454459)~~

**Comment by adamchainz** [comment]
Thanks for the release!

**Pull request merged**
