### PR TITLE
Fixes for Manager.from_queryset(), support for QuerySet.as_manager()

### LINKED ISSUE #265: Add support for QuerySet.as_manager()
Refs https://github.com/typeddjango/django-stubs/issues/19#issuecomment-564764730

### PR DESCRIPTION
**Pull request by mkurnikov**
TODO: 

- [ ] log all new exceptions, instead of crushing the plugin
- [ ] ability to silence errors
- [ ] cleanup the code 

Fixes https://github.com/typeddjango/django-stubs/issues/265
Closes https://github.com/typeddjango/django-stubs/pull/287, closes https://github.com/typeddjango/django-stubs/pull/286, closes https://github.com/typeddjango/django-stubs/pull/272

### CODE REVIEW

**Comment by b0g3r** [comment]
Any progress for this? 🙏

**Comment by sobolevn** [comment]
Related #366

**Comment by jsatt** [comment]
@mkurnikov Any progress?

**Comment by Thorbenl** [comment]
@mkurnikov any progress on this? :)

**Comment by mkurnikov** [comment]
I have very little time for Python development now. I'd only probably find time to finish it (and other PRs) if there's a big need from the community, otherwise, I'll just postpone it indefinitely. 

Could anyone add a thumbs up on this post so I could understand how many people actually need it?

**Comment by syastrov** [comment]
There is a workaround: https://github.com/typeddjango/django-stubs#my-queryset-methods-are-returning-any-rather-than-my-model

**Comment by flaeppe** [comment]
This can probably be closed in favor of #1025

**Pull request closed without merging**
