### PR TITLE
Bump mypy to 0.95x

### PR DESCRIPTION
**Pull request by g-as**
# I have made things!

Allowed mypy 0.95x

### CODE REVIEW

**Comment by sobolevn** [comment]
Can you please bump https://github.com/typeddjango/django-stubs/blob/master/requirements.txt#L13 ?

**Comment by g-as** [comment]
indeed

**Comment by g-as** [comment]
done

**Comment by g-as** [comment]
closing in favor of #939 since @DamianZaremba already updated the tests

**Pull request closed without merging**
