### PR TITLE
5.0: Update `django.contrib.gis.db.backends.postgis.operations`

### PR DESCRIPTION
**Pull request by JaeHyuckSa**
# I have made things!
Update stubs for `django.contrib.gis.db.backends.postgis.operations` for Django 5.0.

- [x] `django.contrib.gis.db.backends.postgis.operations`
    - [x]  `django.contrib.gis.db.backends.postgis.operations.PostGISOperator.check_geography` was added

## Related issues

Refs
- https://github.com/typeddjango/django-stubs/issues/1493

Upstream PR
- https://github.com/django/django/pull/16519

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Just like in `as_sql`: https://github.com/typeddjango/django-stubs/blob/a26f96ade76e2767d11e450cdd67b4ff6e2510bf/django-stubs/contrib/gis/db/backends/utils.pyi#L19 which calls `check_geometry`: https://github.com/django/django/blob/d59066b90c2ef91a956c6682ed3d25bbb31bf216/django/contrib/gis/db/backends/postgis/operations.py#L42

But! `as_sql` also calls `check_raster` which uses mutation :(
https://github.com/django/django/blob/d59066b90c2ef91a956c6682ed3d25bbb31bf216/django/contrib/gis/db/backends/postgis/operations.py#L59-L62

https://github.com/django/django/blob/d59066b90c2ef91a956c6682ed3d25bbb31bf216/django/contrib/gis/db/backends/postgis/operations.py#L79

So, `template_params` is at least `MutableMapping`

**Review by sobolevn — CHANGES_REQUESTED** [review]
I misclicked. This needs to be changed

**Comment by JaeHyuckSa** [comment]
> Just like in `as_sql`:
> 
> https://github.com/typeddjango/django-stubs/blob/a26f96ade76e2767d11e450cdd67b4ff6e2510bf/django-stubs/contrib/gis/db/backends/utils.pyi#L19
> 
> which calls `check_geometry`: https://github.com/django/django/blob/d59066b90c2ef91a956c6682ed3d25bbb31bf216/django/contrib/gis/db/backends/postgis/operations.py#L42
> But! `as_sql` also calls `check_raster` which uses mutation :( https://github.com/django/django/blob/d59066b90c2ef91a956c6682ed3d25bbb31bf216/django/contrib/gis/db/backends/postgis/operations.py#L59-L62
> 
> https://github.com/django/django/blob/d59066b90c2ef91a956c6682ed3d25bbb31bf216/django/contrib/gis/db/backends/postgis/operations.py#L79
> 
> So, `template_params` is at least `MutableMapping`

I appreciate your thorough explanation! Thanks to your guidance, I now have a clear understanding. I've revised the section accordingly and have uploaded the updates. Thank you for your assistance!

**Review by sobolevn — COMMENTED** [review]
Please, also update `.as_sql` method from the base class

**Comment by JaeHyuckSa** [comment]
> Please, also update `.as_sql` method from the base class

Thank you for your guidance in revising it! :)

**Review by sobolevn — APPROVED** [review]
Thanks!

**Pull request merged**
