### PR TITLE
Add `is_active` field to `django.contrib.auth.AbstractBaseUser` model

### LINKED ISSUE #212: Django model field
Hi, I am using django and I here is a bug I encountered, the method `django.contrib.auth.authenticate` returns and instance of `django.contrib.auth.models.AbstarctBaseUser`.

If I check for `user.is_active` pylance claims **Cannot access member "is_active" for type "AbstractBaseUser"** even though it is a defined field on the `AbstractBaseUser` class as shown in the screenshot.

Screenshot from 2020-08-07 14-34-08

-   Language Server version: pylance (v2020.8.0)
-   OS and version: Ubuntu 20.04 64bit
-   Python version: python 3.8.2 (pyenv, venv)

### PR DESCRIPTION
**Pull request by yankyhoffman**
Add the `is_active` property on the `django.contrib.auth.AbstractBaseUser` model as defined in the [Django source code](https://github.com/django/django/blob/master/django/contrib/auth/base_user.py#L52).

## Related issues

- Closes [#212 (Pylance)](https://github.com/microsoft/pylance-release/issues/212)

### CODE REVIEW

**Comment by sobolevn** [comment]
Maybe `is_active: Literal[True] = ...`?

**Comment by yankyhoffman** [comment]
The Django user model defines the `is_active` property and it [defaults](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#django.contrib.auth.models.CustomUser.is_active) to `True`, I wouldn't say it should be defined as `Literal` i.e. a sub class might want to override it.

(Or perhaps I don't yet fully understand the definition of `Literal[True]` (I didn't really use too much types yet, still trying to break into the habit)).

**Comment by sobolevn** [comment]
Yes, `Literal` is too much. It should be `is_active: bool = ...` then! 👍

**Comment by yankyhoffman** [comment]
> Yes, `Literal` is too much. It should be `is_active: bool = ...` then!

Fair point, as this is indeed the point of a property in an abstract class.

I followed your suggestion in my newest commit.

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Ok, we have a problem

> ../../home/travis/build/typeddjango/django-stubs/django-stubs/contrib/auth/models.pyi:81: error: Incompatible types in assignment (expression has type "BooleanField[Union[bool, Combinable], bool]", base class "AbstractBaseUser" defined the type as "bool")

**Comment by yankyhoffman** [comment]
Wow! I see I still have plenty to learn regarding using a typing system on python.

What I don't understand is why doesn't `bool` match the requirements of `db.models.BooleanField`? As I see defined in the [`db.models.fields`](https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/fields/__init__.pyi#L265:L268) its `_pyi_private_set_type` and `_pyi_private_get_type` types should match `bool` (at least as far as I understand).

**Comment by sobolevn** [comment]
I recently saw an issue about that as well: https://github.com/typeddjango/django-stubs/issues/512

Probably, the easiest way for now is to annotate `is_active` as it asks.

**Comment by yankyhoffman** [comment]
I updated the type to reflect the implemented type in the sub class in my latest commit.

I ran `pytest` locally with `dev-requirements.txt` installed and the tests which failed previously have passed, however [1 test](https://github.com/typeddjango/django-stubs/blob/master/tests/typecheck/models/test_inheritance.yml#L94) (out of the 187) has failed, with
```
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings. (diff)
```
at the bottom of the stack trace, might be due to my environment setup..,

**Edit**: It indeed appears that it was due to my environment being different from the testing environment as the test have passed. (I just realized that it might be due to me running the tests on a different version of python.)

**Comment by sobolevn** [comment]
Thanks a lot! I invite you to investigate this field issue further! 👍

**Comment by LanDinh** [comment]
So jumping in on this discussion because this produced a type error on my project \*laugh\*

In my project, I subclass from `AbstractBaseUser` instead of subclassing from `AbstractUser`, because `AbstractUser` defines a bunch of fields that I don't like - and I override the `is_active` attribute as a `@property`.

So at least in my opinion, I think that annotating `AbstractBaseUser.is_active: bool` was the correct thing to do, and that `AbstractUser` is the one who breaks inheritance principles, and should thus receive a `# type: ignore[override]` - so that people who decide to go the `AbstractBaseUser` way can do so without having to add a that type ignore. Should those people end up turning that property into a `BooleanField` instead, that will have been their conscious choice, which means that they should be aware of the type hinting consequences.

BUT before I create a PR for this, I was hoping to get some other opinions on that :)

**Comment by sobolevn** [comment]
@LanDinh your solution implies that all other subclasses of `AbstractBaseUser` would have to use `# type: ignore` when defining `is_active` as a `BooleanField`. Which is not good in my opinion.

For me, this solution seems better.

**Comment by LanDinh** [comment]
Good thing I decided to ask for opinions first. I totally forgot that any mismatch with supertypes will be checked, and not just the most immediate parent...^^ Thanks for reminding me of that!

**Pull request merged**
