### PR TITLE
Fix missing `__init__.py` in django_stubs_ext.db

### PR DESCRIPTION
**Pull request by monosans**
The django_stubs_ext 4.2.0 release does not have a `db` package because it is missing `__init__.py`.

### CODE REVIEW

**Comment by adamchainz** [comment]
@monosans what issues are you seeing? After PEP420, folders without `__init__.py` should still function as packages.

@intgr if this is an issue, let's add https://github.com/adamchainz/flake8-no-pep420 to flake8 configuration.

**Comment by intgr** [comment]
This PR references the issue described here: https://github.com/typeddjango/django-stubs/issues/1450#issuecomment-1525663652

~~I tested `python setup.py sdist` from this branch and it still produced an archive without `db/models.py`. Unless I messed something up.~~

~~I think something needs to be changed in `django_stubs_ext/setup.py`, but I haven't yet looked into it in depth.~~

**Comment by intgr** [comment]
My bad, this PR indeed fixes the issue, thanks!

```
├── django-stubs-ext-4.2.0
│   ├── PKG-INFO
│   ├── README.md
│   ├── django_stubs_ext
│   │   ├── __init__.py
│   │   ├── aliases.py
│   │   ├── annotations.py
│   │   ├── db
│   │   │   ├── __init__.py
│   │   │   └── models.py
```

**Review by intgr — APPROVED** [review]
Thanks for the help!

**Pull request merged**
