### PR TITLE
Issue 309

### LINKED ISSUE #309: Can't assign AnonymousUser to request.user
# Bug report

I'm implementing my own logout routine and need to assign AnonymousUser to request.user like:

```
        if hasattr(request, 'user'):
            from django.contrib.auth.models import AnonymousUser

            request.user = AnonymousUser()
```

## What's wrong
The code above has the error:

error: Incompatible types in assignment (expression has type "AnonymousUser", variable has type "AbstractBaseUser")

## How is that should be

request.user should allow both AnonymousUser and AbstractBaseUser

## System information

- OS: Ubuntu 18.04
- `python` version: 3.6
- `django` version: 2.2
- `mypy` version: 0.761
- `django-stubs` version: 1.4.0

### PR DESCRIPTION
**Pull request by bullfest**
Fixes #309 

Thanks to @kszmigiel that made #354, that this PR is based on.

I also added a `Literal` type annotation to `is_authenticated` as it should always be `False` on an `AnonymousUser` and `True` on an `AbstractBaseUser` per Django's documentation: https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#attributes

### CODE REVIEW

**Comment by bullfest** [comment]
I'll look into that failing test tomorrow :smiley: If anyone knows how to fix it and can save me the hassle of debugging I'd be happy to take advice.

**Review by sobolevn — APPROVED** [review]
THIS. IS. GREAT. STUFF. 🎉

**Comment by kszmigiel** [comment]
@bullfest Great job! Thank you for taking care of finishing what I was not capable ❤️

**Comment by sobolevn** [comment]
This test is failing:

```
test-data/typecheck/test_request.yml::request_object_user_can_be_descriminated Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3749, in accept
  File "mypy/nodes.py", line 1496, in accept
  File "mypy/checkexpr.py", line 1985, in visit_member_expr
  File "mypy/checkexpr.py", line 2003, in analyze_ordinary_member_access
  File "mypy/checkmember.py", line 126, in analyze_member_access
  File "mypy/checkmember.py", line 143, in _analyze_member_access
  File "mypy/checkmember.py", line 225, in analyze_instance_member_access
  File "mypy/checkmember.py", line 376, in analyze_member_var_access
  File "mypy/checkmember.py", line 602, in analyze_var
  File "/home/travis/build/typeddjango/django-stubs/mypy_django_plugin/transformers/request.py", line 11, in set_auth_user_model_as_type_for_request_user
    model_cls = django_context.apps_registry.get_model(auth_user_model)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/django/apps/registry.py", line 205, in get_model
    app_config = self.get_app_config(app_label)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/django/apps/registry.py", line 162, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'auth'.
/tmp/pytest-mypy-co6htmij/main.py:3: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770
/tmp/pytest-mypy-co6htmij/main.py:3: : note: use --pdb to drop into pdb
```

I guess, that it can be solved with https://github.com/typeddjango/django-stubs/blob/80742f43da9deb1197836b3fe8c42e058f361920/test-data/typecheck/models/test_proxy_models.yml#L8

**Comment by bullfest** [comment]
The problem here seems to be that the transformers override whatever type we put on HttpRequest. I don't really understand how the transformers work and can't find any documentation. If anyone have any pointers it'd be appreciated :smile:

**Comment by sobolevn** [comment]
You mean this transformer? https://github.com/typeddjango/django-stubs/blob/master/mypy_django_plugin/transformers/request.py#L9

It works this way (you can later put this into the docstring):
1. `auth_user_model = django_context.settings.AUTH_USER_MODEL` is a full path to a user class
2. `model_cls = django_context.apps_registry.get_model(auth_user_model)` fetches this model class from declared apps (you can probably dig into this method)
3. `model_info = helpers.lookup_class_typeinfo(helpers.get_typechecker_api(ctx), model_cls)` this line uses `mypy` api to fetch type definition by its full name
4. Then we return a new instance of the provided type: `return Instance(model_info, [])`

**Comment by bullfest** [comment]
:boom: :tada: There we go!

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks a lot, @bullfest! This is a really awesome feature!

**Pull request merged**
