### PR TITLE
Make decorator functions transparent to Mypy

### PR DESCRIPTION
**Pull request by intgr**
# I have made things!

By declaring return type as `-> Callable[[_C], _C]`, Mypy can infer that
the decorated function has also the same arguments and return type as
the original.

View functions are constrained to return HttpResponseBase (or any
subclass of it).

Also added typecheck test coverage to most of the cases.

## Related issues
Analogous PR in djangorestframework-stubs: https://github.com/typeddjango/djangorestframework-stubs/pull/60/files

### CODE REVIEW

**Comment by intgr** [comment]
Pushed fixes for tests.

**Comment by intgr** [comment]
Rebased onto latest `master`.

**Review by sobolevn — APPROVED** [review]
Awesome. Thanks!

@mkurnikov do you have any comments?

**Comment by intgr** [comment]
Ping?

By the way, the method I used for annotating decorators has now been documented in mypy:
* https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html#decorators
* https://mypy.readthedocs.io/en/latest/generics.html#decorator-factories

**Comment by sobolevn** [comment]
@intgr can you please the CI?

**Comment by intgr** [comment]
Oh, I had a look at it but I don't know what to do about it. It looks like CI configuration is broken; it fails in the master branch as well (https://travis-ci.com/typeddjango/django-stubs/builds/149232987)

This is the error:
```
Traceback (most recent call last):
  File "./scripts/typecheck_tests.py", line 10, in <module>
    from git import RemoteProgress, Repo
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
The command "python ./scripts/typecheck_tests.py --django_version=3.0
```

**Comment by sobolevn** [comment]
That's because `gitdb` version has changed. And old API is now broken. Can you please help us here? 
1. We can change the `gitdb` version back to the working one
2. We can refactor the source code to fix it (preferable) 

And I would be happy to merge this PR 👍

**Comment by intgr** [comment]
> Can you please help us here?

Finally got around to doing it, opened PR #339.

**Review by sobolevn — APPROVED** [review]
Beams of awesomeness to you 🦄 👍

**Pull request merged**
