### PR TITLE
Bump `django-stubs-ext` dependency to latest

### PR DESCRIPTION
**Pull request by flaeppe**
Aligning release numbers for a `5.0.2` release

Ref: https://github.com/typeddjango/django-stubs/pull/2183#issuecomment-2133304665

### CODE REVIEW

**Review by intgr — APPROVED** [review]

**Comment by intgr** [comment]
Thanks!

**Comment by intgr** [comment]
Should I publish `django-stubs-ext` version 5.0.2 now?

**Comment by flaeppe** [comment]
Yes, go for it!

**Comment by intgr** [comment]
It's out.  https://pypi.org/project/django-stubs-ext/#history

**Comment by flaeppe** [comment]
Cool, I'll create a `5.0.2` release to sync them both up

**Comment by flaeppe** [comment]
`django-stubs==5.0.2` is out now too. https://pypi.org/p/django-stubs#history

Now we just need to fix the trusted publisher for `django-stubs-ext` 🙂

**Comment by intgr** [comment]
I copied the 5.0.1 release notes into 5.0.2 release too, otherwise users might miss it: https://github.com/typeddjango/django-stubs/releases/tag/5.0.2

**Comment by flaeppe** [comment]
Ah, great idea!

**Pull request merged**
