### PR TITLE
Allow Views to return the more generic HttpResponseBase instead of HttpResponse, to allow returning StreamingHttpResponse

### PR DESCRIPTION
**Pull request by LanDinh**
# Allow Views to return the more generic HttpResponseBase instead of HttpResponse, to allow returning StreamingHttpResponse

After having fixed that for DRF already (typeddjango/djangorestframework-stubs#141), I've created this to fix the django-stubs, too.

## Related issues

-

### CODE REVIEW

**Review by sobolevn — CHANGES_REQUESTED** [review]
Great catch!

Can you please write a test for both `HttpResponse` and `StreamingResponse`?

**Comment by LanDinh** [comment]
Tests added!

**Comment by sobolevn** [comment]
One last thing: can you please rebase your code? I have merged quite a lot of stuff! Thanks!

**Comment by LanDinh** [comment]
Done!

**Review by sobolevn — APPROVED** [review]
Great work! Thanks a lot!

**Pull request merged**
