### PR TITLE
5.0: Update `django.forms.formsets`

### PR DESCRIPTION
**Pull request by JaeHyuckSa**
# I have made things!
Update stubs for `django.forms.formsets` for Django 5.0.

- [x] `django.forms.formsets`
  - [x] `django.forms.formsets.BaseFormSet.form_renderer` was added
  - [x] `django.forms.formsets.BaseFormSet.renderer` was added

## Related issues

Refs
- https://github.com/typeddjango/django-stubs/issues/1493

Upstream PR
- https://github.com/django/django/pull/17107

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Btw, why there's no stubtest change?

**Comment by JaeHyuckSa** [comment]
> Btw, why there's no stubtest change?

I've checked on that issue but I couldn't find it. Is there anything I'm missing?

**Review by sobolevn — COMMENTED** [review]
Please, fix them: https://github.com/typeddjango/django-stubs/blob/6ff16d9257bd3de3df8be362d61384972d373317/scripts/stubtest/allowlist_todo.txt#L1296-L1298

**Comment by JaeHyuckSa** [comment]
> Please, fix them:
> 
> https://github.com/typeddjango/django-stubs/blob/6ff16d9257bd3de3df8be362d61384972d373317/scripts/stubtest/allowlist_todo.txt#L1296-L1298

I attempted to modify the` __init__ ` as you suggested, but encountered an error with the `error_class`. I resolved it by applying `ABCMeta`, but I'm not entirely sure if this is the correct approach.


```python
error: django.forms.BaseFormSet.__init__ is inconsistent,
runtime argument "error_class" has a default value of type abc.ABCMeta,
which is incompatible with stub argument type type[django.forms.utils.ErrorList]
```

```python
error_class: ABCMeta
```

**Review by sobolevn — APPROVED** [review]
Ok, let's keep `__init__` ignored for now. It is a complex problem.

Since `ErrorList` extends `UserList` which extends `collections.abc.MutableMapping`.

**Pull request merged**
