### PR TITLE
Add contrib/gis typing

### PR DESCRIPTION
**Pull request by Goldziher**
# Contrib/GIS

This PR adds a full typing of the contib/gis, i.e. "GeoDjango", which for is direly missing for the project i am currently working on 😄 . I used mypy stubgen as a basis and then modified it.

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
😱

**Comment by sobolevn** [comment]
Thanks a lot! We will 100% add this to the next (after a planned one) release.
We have the planned one scheduled for the next few days. 

Can you please fix the CI? Ask for help if you need anything!

One more thing, do you know anyone from Django's side who might be interested in reviewing this PR?

**Comment by Goldziher** [comment]
@sobolevn - was just checking this PR and saw you commented :), thanks for reviewing!. I had to add some more missing typings to the django.db.backends (see the diff), because I encountered issues when running pytest with these. I am now working on fixing the CI and will get it green ASAP.

**Comment by Goldziher** [comment]
As to the second question - i'm afraid I do not know.

**Comment by Goldziher** [comment]
Already merged in different PR

**Pull request closed without merging**
