### PR TITLE
Version 5.0.0 release (django-stubs, django-stubs-ext)

### LINKED ISSUE #2020: Next release planning (5.0.0)
After a few months hiatus, I'm back and planning a release. But don't hold your breath quite yet.

This will be the first release to be officially based on Django 5.0. This **does not mean 100% type coverage for Django 5.0 features**. We are dependent on volunteers to contribute and review updates. Many improvements are already completed and should not be delayed further because we're not perfect yet.

* See #1493 (NB! Not up to date currently, but we're working to update it)

I'm in the process of working through the backlog of unhandled pull requests, there are quite a few. Any additional help in reviewing them would be appreciated.

**Reviewers & maintainers:** To clarify who's handling what, I'd like to ask reviewers to please add themselves as assignee on PRs where they feel comfortable leading the review. (Suggestions welcome for alternative ways of handling PRs)

> image

### PR DESCRIPTION
**Pull request by flaeppe**
Was thinking that we can ship out a new release when possible. So I prepared the needed changes, quite a lot of stuff since https://github.com/typeddjango/django-stubs/releases/tag/4.2.7. Let me know if there's more we need to do for a new release.

- Closes #2020 

Checking the diff of `git diff 4.2.7..master -- ext/` shows that we also need a new release for `django-stubs-ext`.

`django-stubs` should be released automatically since #1950, but this release will be the first using the release flow, hopefully it'll work smoothly.

I don't have access to release `django-stubs-ext` though.

### CODE REVIEW

**Comment by flaeppe** [comment]
Current contents of a release can be found here: https://github.com/typeddjango/django-stubs/compare/4.2.7...6f7a19cf26257fb2da1c65c12a72807f9154dfe7

**Review by sobolevn — COMMENTED** [review]
The only question I have is about version scheme.
Should we use `5.0.0` or `5.0.7.0`?

I would prefer to use `5.0.0` because it gives us more freedom. We can support all patch releases of django, it can give false promises.

**Comment by flaeppe** [comment]
I don't have too strong opinions of either. But just to understand, are you suggesting that we ignore following Django's patch version number and just suffix with a sequence number in each `django-stubs` release?

e.g.

1. `5.0.0.1`  (this release)
2. `5.0.0.2`  (our next release)
3. `5.0.0.3`  (...)
4. ...

**Comment by ngnpope** [comment]
I think we should stick with `x.y.z` where `x.y` follows the main Django version and `z` is the release of `django-stubs` supporting that Django series.

Generally nothing really changes in Django patch releases that would affect the stubs.

**Comment by flaeppe** [comment]
Alright, sounds good. I'll update to `5.0.0`

**Review by sobolevn — APPROVED** [review]
Let's do it!

**Comment by intgr** [comment]
Thanks! Can you wait until tomorrow, I'll do some tests and approve if everything checks out.

**Review by intgr — APPROVED** [review]
Everything looks fine to me.

Are you planning to edit the release notes too?

**Comment by intgr** [comment]
I want to write an announcement about the changes needed due to #1925: `QuerySet` no longer derives from `Collection` but is now `Iterable`.

@sobolevn Looks like I'm missing permissions for that. Can you give permissions to maintainers to add new items in the "Announcements" category of Discussions?

**Comment by flaeppe** [comment]
Cool, thanks for checking. I honestly don't know how much time I able to spend on going through the changes, it's quite a lot. Just don't want to promise something I can't deliver.

**Comment by flaeppe** [comment]
Oh, @intgr I see that you added the `release notes reminder` label. That's clever.

**Comment by intgr** [comment]
> I honestly don't know how much time I able to spend on going through the changes, it's quite a lot.

Indeed, the commitment needed for release notes is what has kept me from actually making a release for so long. Maybe I have made my own life too complicated and we should just simplify the release notes flow.

**Comment by flaeppe** [comment]
Haha, the release notes have been very well written but it's totally fine simplifying for the sake of time and energy saving.

If we want to keep using the `release notes reminder` we might e.g. put those rows at the top under some "interesting changes" header. Then keep e.g. autogenerated notes for the rest.

**Comment by flaeppe** [comment]
I can trigger the release for `django-stubs`, but I need someone with PyPI access to release `django-stubs-ext`.

I'm thinking that I'll merge this and then create a release draft.

**Comment by sobolevn** [comment]
> Looks like I'm missing permissions for that. Can you give permissions to maintainers to add new items in the "Announcements" category of Discussions?

Sure! Looking into this (no idea how this works)

**Comment by flaeppe** [comment]
There's a draft release here: https://github.com/typeddjango/django-stubs/releases/edit/untagged-ec03e0d6d8f60b6172c9

Not sure who's able to see it though

**Comment by sobolevn** [comment]
I've clicked-clacked several buttons, please double check your announcements access @intgr @flaeppe

**Comment by sobolevn** [comment]
@flaeppe looks great! 🚀

**Comment by intgr** [comment]
I posted a longer description and solutions for the QuerySet/Collection change. Let's link that from release notes too:

* https://github.com/typeddjango/django-stubs/discussions/2095

**Comment by flaeppe** [comment]
Great stuff. I added an `Announcements` header in the release notes and a link

@intgr or @sobolevn anyone of you willing to press the big green button? Since (I think) you can release `django-stubs-ext`?

**Comment by intgr** [comment]
I tweaked the language in the "Announcements" section and dropped all dependabot/pre-commit entries from release notes.

Looks like PyPI publishing failed in CI, but I don't understand why. @flaeppe Can we solve this now or should I do the release the old fashioned way?

> Token request failed: the server refused the request for the following reasons:
>
> * `invalid-publisher`: valid token, but no corresponding publisher (All lookup strategies exhausted)

https://github.com/typeddjango/django-stubs/actions/runs/8892716988/job/24417384679

**Comment by flaeppe** [comment]
@intgr Was the trusted publisher set up on the PyPI side? Do you have access to see if it's configured?

It should just be to follow this if it's not: https://docs.pypi.org/trusted-publishers/adding-a-publisher/

Should just be to fill in and post a form

**Comment by flaeppe** [comment]
Owner: typeddjango
Repository name: django-stubs
Workflow name: release.yml
Environment name: release

**Comment by intgr** [comment]
I don't have permissions for that, I guess only @sobolevn can do it.

image

**Comment by flaeppe** [comment]
I see, well, if it wasn't configured and we configure a trusted publisher it should just be to rerun the failed action.

I suppose we need to debug it otherwise and do an old fashioned release.

**Comment by intgr** [comment]
Looks like #1950 was merged without actually doing the setup.

I'll just publish the release manually for now.

**Comment by flaeppe** [comment]
Alright, thank you!

**Pull request merged**
