### PR TITLE
Allow lazy translation strings for constraint 'violation_error_message' arguments, attributes

### PR DESCRIPTION
**Pull request by realsuayip**
# I have made things!

## Related issues

- Improvement on https://github.com/typeddjango/django-stubs/pull/1263

### CODE REVIEW

**Review by intgr — APPROVED** [review]
Looks good to me, thanks

**Comment by intgr** [comment]
I noticed we're missing `default_violation_error_message` attribute in `BaseConstraint`. But that would be a separate PR.

**Comment by intgr** [comment]
@RyanWalker277 maybe if you're interested:

> I noticed we're missing default_violation_error_message attribute in BaseConstraint. But that would be a separate PR.

**Comment by RyanWalker277** [comment]
> @RyanWalker277 maybe if you're interested:
> 
> > I noticed we're missing default_violation_error_message attribute in BaseConstraint. But that would be a separate PR.

Sure! Would raise a PR for this asap.

**Pull request merged**
