### PR TITLE
Extend _AllLimitChoicesTo

### LINKED ISSUE #2442: Error on Field.limit_choices_to with callable
# Bug report

## What's wrong

I get a mypy error when I use a callable on a `ForeignKey.limit_choices_to` argument:

```
error: Argument "limit_choices_to" to "ForeignKey" has incompatible type "Callable[[], dict[str, set[Any]]]"; expected "Q | dict[str, Any] | _ChoicesCallable | None"  [arg-type]
```

My code looks like this:

```python
def limit_to_procedures() -> dict[str, set[Any]]:
    return {"pk__in": {content_type.pk for content_type in ContentType.objects.get_for_models(*AbstractModel.__subclasses__()).values()}} 

def Foo(Model):
  content_type = ForeignKey(ContentType, limit_choices_to=limit_to_procedures, on_delete=CASCADE)
```

## How is that should be

No error should be thrown.

## System information

- OS: Linux
- `python` version: 3.12.7
- `django` version: 5.1.1
- `mypy` version: 1.11.2
- `django-stubs` version: 5.1.0
- `django-stubs-ext` version: 5.1.0

### PR DESCRIPTION
**Pull request by H4rryK4ne**
allow callables which return _LimitChoicesTo

# I have made things!

## Related issues

- Closes #2442

### CODE REVIEW

**Comment by H4rryK4ne** [comment]
I have 2 failing test, but they already fail on the `master` branch:

```
=========================================================================================== short test summary info ============================================================================================
FAILED tests/typecheck/contrib/gis/test_fields.yml::fields_getter_and_setter - 
FAILED tests/typecheck/models/test_inheritance.yml::django_contrib_gis_base_model_mixin_inheritance - 
================================================================================== 2 failed, 444 passed in 482.32s (0:08:02) ===================================================================================
```

Both test fail with 
```
A: Error constructing plugin instance of NewSemanalDjangoPlugin
```

**Review by sobolevn — COMMENTED** [review]
Sorry, what tests are failing? I cannot see any failures here: https://github.com/typeddjango/django-stubs/commits/master/

**Comment by H4rryK4ne** [comment]
> Sorry, what tests are failing? I cannot see any failures here: https://github.com/typeddjango/django-stubs/commits/master/

Sorry ... I meant, they where failing on _my_ machine ...

**Review by sobolevn — APPROVED** [review]
Thank you!

**Pull request merged**
