### PR TITLE
Add validate_constraints method to the Model stub

### PR DESCRIPTION
**Pull request by OvervCW**
What it says in the title.

### CODE REVIEW

**Review by intgr — APPROVED** [review]
Thanks! Looks good.

I looked at the Model class and there are a few more missing methods: get_constraints, serializable_value, prepare_database_save, date_error_message. But not your responsibility unless you want to.

**Comment by OvervCW** [comment]
@intgr Yeah, I noticed that as well. I may submit another PR to add those methods later.

**Comment by intgr** [comment]
@RyanWalker277 FYI if you're looking for more things to do:

> I looked at the Model class and there are a few more missing methods: get_constraints, serializable_value, prepare_database_save, date_error_message. But not your responsibility unless you want to.

**Comment by RyanWalker277** [comment]
> @RyanWalker277 FYI if you're looking for more things to do:
> 
> > I looked at the Model class and there are a few more missing methods: get_constraints, serializable_value, prepare_database_save, date_error_message. But not your responsibility unless you want to.
> 

Thanks a ton! I was looking for some issues to work upon. Will work on this now.

**Pull request merged**
