### PR TITLE
Added `CommandParser` to `commands.__init__`

### LINKED ISSUE #1926: `CommandParser` not in `django.core.management`
# Bug report

I think `CommandParser` should be in `django-stubs/core/management/__init__.pyi`. As of 4.2.7, it's not there: https://github.com/typeddjango/django-stubs/blob/4.2.7/django-stubs/core/management/__init__.pyi

## What's wrong

```python
from django.core.management import BaseCommand, CommandParser
```

## How is that should be

I think we need to add:

```python
from .base import CommandParser as CommandParser
```

## System information

- OS: macOS Ventura 13.5.2
- `python` version: 3.10.13
- `django` version: 3.2.23
- `mypy` version: 1.7.1
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

### PR DESCRIPTION
**Pull request by jamesbraza**
Closes https://github.com/typeddjango/django-stubs/issues/1926

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Do we need https://github.com/django/django/blob/0630ca5725ba5b17c61cd1f6a05dce2660c4724e/django/core/management/__init__.py#L23 as well?

**Comment by jamesbraza** [comment]
Yeah thanks for the suggestion! Implemented it just now 👍

**Comment by jamesbraza** [comment]
Ha now I understand why the `as` statements were there... otherwise `pre-commit` will remove them lolz

**Review by sobolevn — APPROVED** [review]
Thanks!

**Pull request merged**
