### PR TITLE
Improve *HttpResponse.getvalue() types

### PR DESCRIPTION
**Pull request by danifus**
- Makes `StreamingHttpResponse.getvalue()` return type more specific
- Adds missing `HttpResponse.getvalue()` definition

### CODE REVIEW

**Comment by danifus** [comment]
Sorry I think I crossed this with a different branch. Let me fix that up and try again

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Related to #393

**Comment by danifus** [comment]
Ok, that is cleaner now :)

**Comment by sobolevn** [comment]
Thanks a lot!

**Pull request merged**
