### PR TITLE
Upgrade dev-requirement for pytest-mypy-plugins

### PR DESCRIPTION
**Pull request by brianhelba**
This fixes broken CI.

### CODE REVIEW

**Comment by brianhelba** [comment]
CI is breaking because of the release of [`setuptools` v58](https://setuptools.pypa.io/en/latest/history.html#v58-0-0), which dropped support for the `use_2to3` argument. This caused the long-dead `pystache` to fail to build.

`pytest-mypy-plugins==1.7.0` still requires `pystache`, whereas `pytest-mypy-plugins==1.9.1` no longer has this requirement.

**Comment by brianhelba** [comment]
@sobolevn For some reason, the Python 3.8 test is failing. It looks like it might be an issue with `pytest-mypy-plugins`, but I don't understand the error message.

**Comment by sobolevn** [comment]
Replaced with #734

**Comment by sobolevn** [comment]
Thanks a lot for working on it! 👍

**Pull request closed without merging**
