### PR TITLE
Fix signature of `ModelAdmin.construct_change_message`

### PR DESCRIPTION
**Pull request by youtux**
The `form` argument was incorrectly typed.

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Why do you think so? Is this documented? There's also one more place in `admin/utils.py` where the same type is used.

**Comment by youtux** [comment]
The method belongs to generic ModelAdmin class; it makes no sense for it to take an AdminPasswordChange form. The implementation just require any instance of Form

**Comment by sobolevn** [comment]
Got it, please address the second comment :)

**Comment by youtux** [comment]
Done in ~~605cddf9~~ 80f199f5

**Review by sobolevn — APPROVED** [review]
Thanks!

**Pull request merged**
