### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by adamchainz**
# I have made things!

Add new project logo.

## Related issues

As discussed in #1398.

### CODE REVIEW

**Review by intgr — APPROVED** [review]
Looks great to me 👍

**Comment by sobolevn** [comment]
Awesome! Thanks a lot 🎉

**Comment by sobolevn** [comment]
What should we do with the group logo? 🤔

**Comment by intgr** [comment]
I think let's replace it with the double-checkmark ticket icon. Just remove the "django-stubs" text.

**Comment by sobolevn** [comment]
Can someone please help me with the image? :)
I will change it asap.

**Comment by intgr** [comment]
My graphics skills are a bit rusty but I think I did it. Exported as 512x512 px PNG so GitHub can scale it as necessary. I deliberately didn't center it perfectly, but aligned it to a pixel boundary in a 32x32 grid, so it renders better as an icon. 

| PNG (use this one) | SVG |
|-----|-----|
| icon | icon |

**Comment by sobolevn** [comment]
Done, thank you!

**Pull request merged**
