### PR TITLE
Update mypy to 1.11.0

### PR DESCRIPTION
**Pull request by sobolevn**
Closes https://github.com/typeddjango/django-stubs/pull/2267

### CODE REVIEW

**Comment by sobolevn** [comment]
Blocked by https://github.com/python/typeshed/pull/12404

**Comment by flaeppe** [comment]
Could perhaps this breakage bring an argument to include `django-stubs` in `mypy_primer`? I think it would be possible since https://github.com/hauntsaninja/mypy_primer/commit/83721d5df580c78f6749eb61c4f90ea4a03252df, ref https://github.com/hauntsaninja/mypy_primer/issues/8

**Comment by sobolevn** [comment]
cc @hauntsaninja
What's your opinion?

**Comment by hauntsaninja** [comment]
Yeah, PR welcome!

**Comment by sobolevn** [comment]
https://github.com/hauntsaninja/mypy_primer/pull/124

**Comment by lordoffreaks** [comment]
Hi! Thanks a lot for the work! 

I can see `5.0.3` created in the repo but can't see it in https://pypi.org/project/django-stubs/ or in https://github.com/typeddjango/django-stubs/releases ... is there anything I can do to move it there?

Thanks!

**Comment by sobolevn** [comment]
It is not created, I just added it to the docs, so we won't forget.

@flaeppe maybe we should make a new release?

**Comment by flaeppe** [comment]
Sounds good, I've opened #2274

**Pull request merged**
