### PR TITLE
Prepare for a release `5.0.3`

### PR DESCRIPTION
**Pull request by flaeppe**
Time for `5.0.3`

## Related issues

Ref: https://github.com/typeddjango/django-stubs/pull/2269#issuecomment-2250690058

### CODE REVIEW

**Comment by flaeppe** [comment]
@sobolevn do you think we could include #2252 as well?

**Comment by sobolevn** [comment]
@flaeppe I haven't looked at it yet. Maybe let's schedule it for the next one? It is quite complex, I don't want to do a last minute review :(

**Review by sobolevn — APPROVED** [review]
Thank you!

**Comment by flaeppe** [comment]
> @flaeppe I haven't looked at it yet. Maybe let's schedule it for the next one? It is quite complex, I don't want to do a last minute review :(

No worries, lets save it for the next one

**Comment by flaeppe** [comment]
I've released [5.0.3](https://github.com/typeddjango/django-stubs/releases/tag/5.0.3) just now:

- https://pypi.org/project/django-stubs/5.0.3/
- https://pypi.org/project/django-stubs-ext/5.0.3/

**Comment by sobolevn** [comment]
Thank you!

**Pull request merged**
