### PR TITLE
Updated the BaseQuerySet to Django 3.2

### PR DESCRIPTION
**Pull request by maximmasiutin**
There is no _BaseQuerySet in Django 3.2 LTS.

The .pyi files didn't match the .py files. 

Besides that, the static code analyzer Pyre gave an error: 
`The modelled function "django.db.models.query.QuerySet.get" is an imported function, please model "django.db.models.query._BaseQuerySet.get" directly.`

With the above patch, the query.pyi  matches the query.py from the Django 3.2 LTS. 

I have also updated some other files just to use the QuerySet instead of the non-existing _BaseQuerySet.

### CODE REVIEW

**Comment by maximmasiutin** [comment]
How can I fix these errors?

```
platform linux -- Python 3.7.10, pytest-6.1.1, py-1.10.0, pluggy-0.13.1 -- /opt/hostedtoolcache/Python/3.7.10/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/django-stubs/django-stubs, configfile: pytest.ini, testpaths: ./tests, ./django_stubs_ext/tests
plugins: mypy-plugins-1.6.1
collecting ... collected 212 items

tests/test_error_handling.py::test_misconfiguration_handling[missing-file] PASSED
tests/test_error_handling.py::test_misconfiguration_handling[missing-section] PASSED
tests/test_error_handling.py::test_misconfiguration_handling[missing-settings-module] PASSED
tests/test_error_handling.py::test_misconfiguration_handling[no-settings-given] PASSED
tests/test_error_handling.py::test_correct_configuration PASSED
tests/typecheck/test_config.yml::pyproject_toml_config FAILED
tests/typecheck/test_config.yml::generate_pyproject_toml_and_settings_file_from_installed_apps_key FAILED
tests/typecheck/test_config.yml::add_mypy_path_to_package_search PASSED
tests/typecheck/test_config.yml::add_mypypath_env_var_to_package_search PASSED
tests/typecheck/test_forms.yml::no_incompatible_meta_nested_class_false_positive FAILED
tests/typecheck/test_forms.yml::formview_methods_on_forms_return_proper_types FAILED
tests/typecheck/test_forms.yml::updateview_form_valid_has_form_save FAILED
tests/typecheck/test_forms.yml::successmessagemixin_compatible_with_formmixin FAILED
tests/typecheck/test_helpers.yml::transaction_atomic_contextmanager FAILED
tests/typecheck/test_helpers.yml::transaction_atomic_decorator FAILED
tests/typecheck/test_helpers.yml::mark_safe_decorator_and_function PASSED
tests/typecheck/test_import_all.yml::import_all_modules FAILED
tests/typecheck/test_mail.yml::check_email_message_attach FAILED
tests/typecheck/test_request.yml::request_object_has_user_of_type_auth_user_model FAILED
tests/typecheck/test_request.yml::request_object_user_can_be_descriminated FAILED
tests/typecheck/test_request.yml::request_object_user_without_auth_and_contenttypes_apps FAILED
tests/typecheck/test_request.yml::request_object_user_without_auth_but_with_contenttypes_apps FAILED
tests/typecheck/test_request.yml::subclass_request_not_changed_user_type FAILED
tests/typecheck/test_request.yml::subclass_request_changed_user_type FAILED
tests/typecheck/test_settings.yml::settings_loaded_from_different_files FAILED
tests/typecheck/test_settings.yml::global_settings_are_always_loaded FAILED
tests/typecheck/test_settings.yml::fail_if_there_is_no_setting FAILED
tests/typecheck/test_settings.yml::override_default_setting_with_different_type_in_the_different_module FAILED
tests/typecheck/test_shortcuts.yml::get_object_or_404_returns_proper_types FAILED
tests/typecheck/test_shortcuts.yml::get_user_model_returns_proper_class FAILED
tests/typecheck/test_shortcuts.yml::check_render_function_arguments_annotations FAILED
tests/typecheck/test_shortcuts.yml::check_redirect_return_annotation FAILED
tests/typecheck/test_views.yml::login_form_form_valid_typechecks FAILED
tests/typecheck/contrib/admin/test_options.yml::test_full_admin FAILED
tests/typecheck/contrib/admin/test_options.yml::test_fieldset_workaround_regression FAILED
tests/typecheck/contrib/admin/test_options.yml::errors_on_omitting_fields_from_fieldset_opts FAILED
tests/typecheck/contrib/admin/test_options.yml::errors_on_invalid_radio_fields FAILED
```

Please help!

**Comment by sobolevn** [comment]
Hi, @maximmasiutin! This is a hack we use to make this plugin work. I am not sure that it can be just removed.
By convention we use `_` prefixed names for stuff like this.
Thanks a lot for your time though!

**Comment by maximmasiutin** [comment]
At least there is neither _BaseQuerySet nor BaseQuerySet in the Django 3.2, the latest version.

There is just the QuerySet. 

So I have modified the .pyi files, and they now exactly match the .py files in those lines related to the QuerySet.

Do you mean the the mypy-plugins-1.6.1 does work incorrectly unless you use the _BaseQuerySet hack?

**Comment by sobolevn** [comment]
Related https://github.com/typeddjango/django-stubs/issues/608

**Comment by maximmasiutin** [comment]
@sobolevn 

> Related #608

There is no _BaseQuerySet in Django 3.2 LTS: the .pyi files of django-stubs didn't match the .py files of django when it comes to QuerySet. Thus the static code analyzer Pyre https://github.com/facebook/pyre-check gives errors as described in my initial message. Could you please consider reopening the pull request?

**Comment by sobolevn** [comment]
Yes, @maximmasiutin, we need to remove it. See #608

But, it is much more complex than just removing it, because we need to model `ValuesQuerySet`

**Pull request closed without merging**
